Feature/create endpoints 13
Heugene/Softserve-practice-2024 pull request #14
Opened 2024-05-13 18:00 UTC by emiliiakazakova

2024-05-14 14:36 UTC, DenysKushnyr requested changes
Потрібно додати валідацію вхідних даних у кожному контролері

2024-05-14 14:36 UTC, DenysKushnyr commented on src/API/Controllers/LocationsController.cs
> +        public async Task<ActionResult<Location>> GetLocation(int id)
Потрібно шукати локації за cityId, а не за locationId. Тобто повертатися має список location для конкретного city.

2024-05-14 14:57 UTC, Heugene requested changes
В цілому ок, але потрібно виправити зазначені Денисом проблеми із пошуком локації за айді міста та зробити базову валідацію полів об'єктів (коректні назви, перевірка на від'ємність, якщо вона не допустима, перевірка на входження значення до діапазону enum тощо).

2024-05-20 20:47 UTC, Heugene commented
Game over, доведеться залити на мастер без доробок, щоб набрати більше очок

2024-05-20 20:49 UTC, merged